/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.estudo.performance.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CostumerPersonalRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6373514362550898301L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CostumerPersonalRequestAvroModel\",\"namespace\":\"com.estudo.performance.model\",\"fields\":[{\"name\":\"cpf\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CostumerPersonalRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<CostumerPersonalRequestAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CostumerPersonalRequestAvroModel> DECODER =
      new BinaryMessageDecoder<CostumerPersonalRequestAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CostumerPersonalRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CostumerPersonalRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CostumerPersonalRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CostumerPersonalRequestAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CostumerPersonalRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CostumerPersonalRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CostumerPersonalRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CostumerPersonalRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String cpf;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CostumerPersonalRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param cpf The new value for cpf
   */
  public CostumerPersonalRequestAvroModel(java.lang.String cpf) {
    this.cpf = cpf;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cpf;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cpf = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'cpf' field.
   * @return The value of the 'cpf' field.
   */
  public java.lang.String getCpf() {
    return cpf;
  }


  /**
   * Sets the value of the 'cpf' field.
   * @param value the value to set.
   */
  public void setCpf(java.lang.String value) {
    this.cpf = value;
  }

  /**
   * Creates a new CostumerPersonalRequestAvroModel RecordBuilder.
   * @return A new CostumerPersonalRequestAvroModel RecordBuilder
   */
  public static com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder newBuilder() {
    return new com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder();
  }

  /**
   * Creates a new CostumerPersonalRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CostumerPersonalRequestAvroModel RecordBuilder
   */
  public static com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder newBuilder(com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder other) {
    if (other == null) {
      return new com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder();
    } else {
      return new com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new CostumerPersonalRequestAvroModel RecordBuilder by copying an existing CostumerPersonalRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new CostumerPersonalRequestAvroModel RecordBuilder
   */
  public static com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder newBuilder(com.estudo.performance.model.CostumerPersonalRequestAvroModel other) {
    if (other == null) {
      return new com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder();
    } else {
      return new com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CostumerPersonalRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CostumerPersonalRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<CostumerPersonalRequestAvroModel> {

    private java.lang.String cpf;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cpf)) {
        this.cpf = data().deepCopy(fields()[0].schema(), other.cpf);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing CostumerPersonalRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.estudo.performance.model.CostumerPersonalRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.cpf)) {
        this.cpf = data().deepCopy(fields()[0].schema(), other.cpf);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'cpf' field.
      * @return The value.
      */
    public java.lang.String getCpf() {
      return cpf;
    }


    /**
      * Sets the value of the 'cpf' field.
      * @param value The value of 'cpf'.
      * @return This builder.
      */
    public com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder setCpf(java.lang.String value) {
      validate(fields()[0], value);
      this.cpf = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cpf' field has been set.
      * @return True if the 'cpf' field has been set, false otherwise.
      */
    public boolean hasCpf() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'cpf' field.
      * @return This builder.
      */
    public com.estudo.performance.model.CostumerPersonalRequestAvroModel.Builder clearCpf() {
      cpf = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CostumerPersonalRequestAvroModel build() {
      try {
        CostumerPersonalRequestAvroModel record = new CostumerPersonalRequestAvroModel();
        record.cpf = fieldSetFlags()[0] ? this.cpf : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CostumerPersonalRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CostumerPersonalRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CostumerPersonalRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<CostumerPersonalRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.cpf);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.cpf = in.readString();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.cpf = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










